apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
    namespace: umami
type: Opaque
stringData:
    postgres-db: ENC[AES256_GCM,data:EFP1bsc=,iv:8f0281f8PDv54jkthWHuIgteZYECOROHJb7IrS2tzxM=,tag:tIqbVIvgVNiKLWAbbAOYZA==,type:str]
    postgres-user: ENC[AES256_GCM,data:naCXJmA=,iv:UnqnErzo6w58yGL/KEvzmHIH9rybN5Vu/yK1LMX9GS8=,tag:FPZKie2RbPp1gd/OCN3W+Q==,type:str]
    postgres-password: ENC[AES256_GCM,data:4Fo9FZC4DTySd4iiQH5qRMaZWIjfQM21T4c0OE8kKXhMUiw5g0/+sNBNA0e+sApKkvX8zr9tNO8hw5FzpM9dlA==,iv:uN1xG72XSqR2hA7ypJSo/ihbwbKmkQjkJUrLTbyfCpc=,tag:Dxhs6XRQqXCvf7OpBwL5qg==,type:str]
    database-url: ENC[AES256_GCM,data:j5UCzZAmXOL7mLW4A7WQ1i6cckz1y5rJ0vJ4AzzV7QjbVO29Z8hC3jsF8hWgZpDsgR0r3caoSJ8Myrt8ONWzHqBf1HeDlS9ZDd6cbnp4n1Q+qxA92vAdhxIRPK8Fxrm+m7IVeJIUkg==,iv:0gMcjL1bR+EgnvL7Y9ZxmkMqwAXQUOdb6X6KrPih0II=,tag:t7Y0ZzLbWZt8eJZvWyv6pA==,type:str]
    app-secret: ENC[AES256_GCM,data:jhYPNWDUPU21WTfHDUrKVuaoRg4mn0AuHExo3CPRBTthHzvQhwBed1/Ury3VevylVENmOuIXV13zWqqtgVrRrw==,iv:dk6E1BSezARFbqZ76GyJbxXyW92IOuT9GOjf85o5dlk=,tag:NKlBegk38tCdUL3VcA/PLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cXh5Nm00NmVuSk9QUFhH
            dHpVNWpvc0FybmtlU3hja25ORUdncTJiR2pzClY4Q2FnS0dMZll3cStLcVRZQTkw
            djJ5cVhvQnN3Q1kwYUJpclQ5V3ZXRmcKLS0tIHY4MnNBMnY4U2tndXI3bWpIRHda
            WVNjOFBEL1lsQXFtV0RUa0F4aXREVzgKwHEVeg5CfVb7kRbReedgF1Z6gU+NWRL1
            QCkcBSafaItu7hGyFrpzYdfqSzMbF1bjB9hkH7ITxBIcTgP46Ygp5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T15:10:44Z"
    mac: ENC[AES256_GCM,data:JQedWNu6cfZS9r28HVHi3sLyMQHBwUGsdS0+VruOHn6qXiimqp9MXDvPrWPH2+cSLjskVIOE1l4h1qaoeg/IKfMsTrfbXT2fmQdWfhr7GOmq0qFhJoZ+WAET8BGGAG12UX20yotZxDRXhIxGynSaVRzz5VaWsUzVT/2bXnQQ+tA=,iv:/zhnnR/rwV2rG29ab7dTCaMoULMbO3rcKxMCM5i7fwU=,tag:KvMHpmT7Yve2mB4EFRi8ug==,type:str]
    version: 3.13.2
