apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-cirthe-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:QW1gkQ7CsZYZqvt3hQ7mnFTsFvB/P6gRSEL1giThnbEj7I16/YsrOzkoRrOuBfMz1rIrt1o=,iv:6YwpOmWcJfLKk7Nw/om8Sl6bf/vnoNCr5cys9bgkQAc=,tag:H4O5I4nLY3HGLqTq1NpP+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcEp6clhkOG5qKzhzTko0
            L0NyUmZXcStNdytDT1JpWFRjc2gwVmZ4RFNvCkpieCtkRkVrekJoNTlXNnNSZmJ2
            U2Zad3Z1akpUUzVacW5ETEFidDFDVUEKLS0tIG1FNC9Ea1lWRVlWZndmb29NdC8y
            c2ZoWEt1R3JTeWZjVlBrZzByMzY5MGcKpZb092A2Jn8jWS/Bc5GomMCcTlEcNyQR
            FPyRzATptGQ+f7Ur7e8g6+JPSbBjopdkaCOPKOXF3mjeFmjlD579vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T14:09:08Z"
    mac: ENC[AES256_GCM,data:QFR4pGPYzwPsd0Cxx0bj/mP3c1OzJkMBmqI3xDZxoie9n+HcjjjCJIrqk1GDJ0tAur2CV6xG14xMUI3r/T+7SJuOJCAR6zLYrEoH/RtYxj53wnu3AA+1133dTf50vDswKQM5wxtu+RTAvDDKkrSSl06/SgfSy1Vq8ZBd7QRHJMA=,iv:kYp2Ng7jmqgdWUAzdiXLz08ZS7a2b+rE8Ol3c8yncrI=,tag:831thQ6xqY6bT6FW2oY31g==,type:str]
    version: 3.13.2
