apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-cirthe-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:60qSejqRD2wL7BhZmLPqeDsMue3NYIhELmUhIA5/WUM=,iv:cJ0GQDdLpg5HNrk+p5Idq1EUJejl3aiNSA3lzfms67o=,tag:+dgYR3IjB7FEVUhaX2kZEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXozYW1SS0ovSlZKNHVX
            QlRJdVQzZTVyaHRSVlgvNjIydUdld2N6ZEM4CmNQR3orS0ticmN2YW15eUJPUDF0
            MW04SXdwMUtVSjM1bEdUSlpWT0ZOVEkKLS0tIGRtTElRSlJJSnJDUzRnaEFBVHFt
            VlQ2SjNiNU1nYjl4YUNjdmhyNXBDSmcK7cKHtfK+/Qui+Df0qM5FlD3xulXABhCI
            EtRI+PNeibCc9fYaKiDRMiQF/EbUDEfY1LqxtlcpR/RuKGkoQLFJYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T13:01:39Z"
    mac: ENC[AES256_GCM,data:y65YzqXuNIWiym7l89yPNdSoxYS+NlZUCe2YblniGW1GhI7PuGUBfxu4g9ZB21wSiAIC0NS8aflKbVBPguFPmFhYRsHoad4VXfDMmSh4bhkbbf4/duuNyObPpIdmLtK3VGt1dbXo/OOVWRC3MI9DHgwMSrWNmE+R1Crdnu66Pss=,iv:XF/ooXpGo9Xgf2RMwBwqKOXaDbx7X8Ka/HiB3rGxwpQ=,tag:b9Y9H5RCMjyIm/AkYvXT7Q==,type:str]
    version: 3.13.2
