---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: voxels-demo-tls
  namespace: voxels-demo
spec:
  secretName: voxels-demo-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - voxels.primed.io

