apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:G2v7Noo9ChruM7NmwERWIfi935wcdN9Ptc53PVCrxu/qNKq8n6YICkKkTEuAI1iIL4s14T5p2Itd3z2OOxWbLWdPpQgw8xa791uD89e2FQA/U2zCkTGOYgi6MsCX1m0v7BHTH04v74/bW0CIdXBv0PHJj0UcuslDVglcknsaFNb2mkq2hfL2dzTjlnOuW/gOky/SEzU3S2r/t1/tcwWEaBO9lfLgNWaitu4ap3JL9s46YbBzmd5wafwZn7kVhFY9a2iXClEX5jCUxkA2jdSAYlsZo3M0qRifPMktfJQRkJG0J0SG,iv:qrqYmOI8rMPD+YdzZ96Sq8zuKrG81i6PybOscs8uftg=,tag:zwV0UimiJhoZRAAkecxZig==,type:str]
kind: Secret
metadata:
    name: ghcr-voxels-pull
    namespace: voxels-demo
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6amx1U3lJU1ZZSm1Ydnh0
            Y3JzNll2OGY3TU1PUjF6aDh4a0tPTG9VZFU0CkdFdnpOYWFGQTZsT0VLSE9iWUNL
            dFNWZ2VyeVFmU1NGQ2VXenBQMVprL28KLS0tIFZnNjZQQzFFSDEvRGUzRjVBbytr
            N21OcmM0b1lyWVZIQll4SXFKK2RIamcKdQ2q9saHWTtGSwauvMjD33SStiSSCF6B
            41JsX9ctezw6w4ndr1Y3XzhbBeLpvAoP6JMu+kMnbWG4zd/R6gHNKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T17:44:11Z"
    mac: ENC[AES256_GCM,data:qDqqngSaaAoKrqOtBFOpWY6g/tB9zi8Eh/CnfquvnlNRo4r3FNNx2sXqLGmgHdDiytLXRaEFeCBv6315hFP7gJjHgaL2ryglJs1LjUQC8FNt3ANFcSGliUSm0rZJ8vRYOcTgOF8dyboG2GTMa+NFvQOQyZDEvO46at40ffznCyY=,iv:0Xi1ev4Yx7T17FVE5ruQhUyksB5nr/rHu4NqW+/Ic8Q=,tag:jotkODxmLq74p068H+IWrA==,type:str]
    version: 3.13.1
