---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rene@primed.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
          # Keep cert-manager compatible with a default-deny egress posture:
          # propagation checks query via in-cluster DNS instead of external authoritative nameservers.
          recursiveNameservers:
            - 10.43.0.10:53
          recursiveNameserversOnly: true
        selector:
          dnsZones:
            - primed.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rene@primed.io
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
          recursiveNameservers:
            - 10.43.0.10:53
          recursiveNameserversOnly: true
        selector:
          dnsZones:
            - primed.io
