---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls
  namespace: immich
spec:
  secretName: immich-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - photos.primed.io
