---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cifs
  resources:
    requests:
      storage: 1Ti
  volumeName: immich-hetzner-storagebox
