---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
    owner: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
        owner: platform
      annotations:
        linkerd.io/inject: "disabled"
    spec:
      priorityClassName: monitoring
      enableServiceLinks: false
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:v2.5.2
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: MACHINE_LEARNING_HOST
          value: "0.0.0.0"
        - name: MACHINE_LEARNING_PORT
          value: "3003"
        - name: MACHINE_LEARNING_WORKERS
          value: "1"
        - name: MACHINE_LEARNING_WORKER_TIMEOUT
          value: "120"
        volumeMounts:
        - name: cache
          mountPath: /cache
        resources:
          requests:
            cpu: 400m
            memory: 1.5Gi
          limits:
            cpu: 800m
            memory: 2.5Gi
        livenessProbe:
          httpGet:
            path: /ping
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: immich-ml-cache
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
spec:
  selector:
    app: immich-machine-learning
  ports:
  - port: 3003
    targetPort: 3003
    name: http
