---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:zcSnkPNWv897WYCfD1tdkqJ2+oOuqdP1iN7OxtfIm1J2SkhV7W9aKxaKkSH2HAHkdSdZt97Nqy7Y1ga5m7/bxfdnxK/cnnYA34KRXbR47uynI2blU7YiO0w4+bZsXhMllNjDPghIT03zpgrZwwZpXyu9yly/UZe1zNJOWCKwqU9N0sFzltzcYtDkIchuGjEPXBtj76RwXAkhbN7rWx0PUlG17RvvLQkMeh1MH9yaI0Oo77MKUO48Uct+JpFynHLhGxCy38+K1ysFdMn1+p7+AWvHjLVq9DTZoc2FtIH3m7zk3URv,iv:ZCYwEeARR1pTl9bXUodOzwe/Yf7dwgJxWzt3d9i4cm4=,tag:uG5OmNCguu/ro/N3gXM91g==,type:str]
kind: Secret
metadata:
    name: ghcr-tarka-pull
    namespace: tarka
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbnIxTE9rbjJ0Tis1Y3Jy
            SEpNQURPQXcyYUplY09neHptcDl0MjVXUzM4ClplYjZXSmNMOWl2VEYzcHdqb0pY
            b1M2UmlDUFdHNjZqbTRSTDYrU1ZpZzAKLS0tIGFQcEhMUHJFay9NSFplQm51WHFW
            SDJtWmFHY2tEb1dYelFxWGxVVWFqUE0KjZ+hc7F0NXVy5v0p6rcJndMzgdT99mfd
            PoON4wgJ7bAccInc37t1TV30nhsj4prlF0nn+Qx8813OP97DrdtTMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T11:07:41Z"
    mac: ENC[AES256_GCM,data:CkoOSK0eTlGLkaIgARJdhlAiDrumVMOYeAMy/njodBlcXCq2l+TDTvxBut1cq9ASp04qab92B1VDQ24wRpkQ6mfqFZWDh5mIMjBRR65gZ3vYuzNQhj9X6iPNuI8ldYpbijkrA8zTXK4cgOU/wzcIZUkOui23Y7dgztZY3+NnnDQ=,iv:vcQQv7nF4w9t5zVNl8vXE4mZ7HniytYVztEA/2XG2nE=,tag:78RA0MV+A00XBW55U97Few==,type:str]
    version: 3.13.2
