---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tarka
  namespace: tarka
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nicholson31tarka.com`) || Host(`www.nicholson31tarka.com`)
      kind: Rule
      services:
        - name: tarka
          port: 8080
  tls:
    secretName: tarka-tls
