---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tarka
resources:
  - namespace.yaml
  - ghcr-pull-secret.enc.yaml
  - deployment.yaml
  - issuer.yaml
  - ingressroute.yaml
  - certificate.yaml
  - network-policies.yaml
images:
  - name: ghcr.io/cogfor/nicholson31tarka.com
    newName: ghcr.io/cogfor/nicholson31tarka.com
    newTag: sha-bbc7fc1d0a86b9e0752be80f0f10cf4e381021b5
    digest: sha256:93280c07cc0505a146360ae989c69a2410e51894c4757262cbbbb7db093bbb8e
replicas:
  - name: tarka
    count: 2
