---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tarka
resources:
  - namespace.yaml
  - ghcr-pull-secret.enc.yaml
  - deployment.yaml
  - issuer.yaml
  - ingressroute.yaml
  - certificate.yaml
  - network-policies.yaml
  - pod-disruption-budget.yaml
  - shared-assets-pvc.yaml
configMapGenerator:
  - name: tarka-asset-sync
    files:
      - sync-assets.sh=scripts/sync-assets.sh
    options:
      labels:
        app: tarka
        owner: platform
images:
  - name: ghcr.io/cogfor/nicholson31tarka.com
    newName: ghcr.io/cogfor/nicholson31tarka.com
    newTag: sha-d96d2e1fa9405a11c063d95e68ad355ad942ea46
    digest: sha256:999e8f7381e1e8a3bf26b268a942060824a6fa40023bd5a1676935abbdc93956
replicas:
  - name: tarka
    count: 2
