---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tarka
resources:
  - namespace.yaml
  - ghcr-pull-secret.enc.yaml
  - deployment.yaml
  - issuer.yaml
  - ingressroute.yaml
  - certificate.yaml
  - network-policies.yaml
images:
  - name: ghcr.io/cogfor/nicholson31tarka.com
    newName: ghcr.io/cogfor/nicholson31tarka.com
    newTag: sha-ee3ad81dee18c72e9c691dd91b99c92a3485e65b
    digest: sha256:75183798210d2b0ea506cd9ac25daa5b8d509f1ade6a3a79c03b3857438d2160
replicas:
  - name: tarka
    count: 2
