---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tarka-shared-assets
  namespace: tarka
  labels:
    app: tarka
    owner: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
