---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: "v1.16.0"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
      interval: 12h
  values:
    # Enable the SMB CSI driver
    controller:
      replicas: 1
    node:
      # DaemonSet to ensure CSI node plugin runs on all nodes
      maxUnavailable: 1
