---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-auth
  namespace: tailscale
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
  annotations:
    kubernetes.io/service-account.name: tailscale-auth
type: kubernetes.io/service-account-token
# Connector is not needed for exposing services.
# Services are exposed via annotations on the Service resource itself.
# See: clusters/production/authentik/ldap-tailscale-service.yaml
#
# This file can be used later if you want to set up subnet routing or exit nodes.
