---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cifs
  resources:
    requests:
      storage: 1Ti
  volumeName: nextcloud-hetzner-storagebox
