apiVersion: v1
kind: Secret
metadata:
    name: hetzner-cifs-credentials
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:uIW637aKEebSzlkx,iv:vMoLJ1gNNjosnnkNpWwVOepSxDwKvwSmPWF7QFGEY74=,tag:dfJwwX/w6hXfzKQ6C46WsQ==,type:str]
    password: ENC[AES256_GCM,data:DFUGTgTI9IkZd1PJ5tISjtWLH0w=,iv:WTDlYJmRdyF2rcFc6FtshVz4cDZeNPOawKeWZCaRCfc=,tag:QGOCFchRk6PVU2+WFZ0Zdw==,type:str]
sops:
    age:
        - recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocFBja0xKRVZ5d28yZ1M3
            Yk81RjlQc3pRYms2SU01S2hnR3BHa2JFUGdjCmZuQ3JvbEZ4ZW9rT1R2ZmYvTG9Z
            YzMvSUhRc1BadlF1dzd0bVBjSm1CWUUKLS0tIEZMTlZnalBqK3hnYlV3dkkyc1Vh
            anlGZlRJRjN2SUN4WEs1WTVZejd0YVEKhj2FGMi7l+PCW9oQ4wE6F0X9LnfbZHB8
            6SelkTguIbVcTjRE7cMbEeGWO+lTR2aStjB4nGBDBVyNOC+D36nNaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:28:02Z"
    mac: ENC[AES256_GCM,data:cGKcgD/twwckSFr4GIZeUy1stGaIREEWpoUO+p5QHwi+gc/eerIUSdkddj6VCWOgZlChjsMyhpk/17fYcV0jA+jtE6iCwnrFrz4lnrOTr21kHHs7Vn4/NWzQ6uGWX9qfiPpLawRjfw6EPVYbS8/vh+YziS0pG3wRf85fkNYp5+M=,iv:D6lwhcKRm8PB738jePHj3CAVs1TWyT1/vfmbzKtzlnE=,tag:ICLNXjU6wPrcKVL3E3Yrqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
