---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-postgres-backup
  namespace: backup
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: docker.io/postgres:16-alpine
            command:
            - /bin/sh
            - -c
            - |
              set -e
              DATE=$(date +%Y%m%d-%H%M%S)
              BACKUP_FILE="paperless-db-${DATE}.sql.gz"

              # Dump database
              PGPASSWORD="${POSTGRES_PASSWORD}" pg_dump \
                -h postgres.paperless-ngx.svc.cluster.local \
                -U ${POSTGRES_USER} \
                -d ${POSTGRES_DB} \
                | gzip > /tmp/${BACKUP_FILE}

              # Upload to S3
              apk add --no-cache aws-cli
              aws s3 cp /tmp/${BACKUP_FILE} \
                s3://${S3_BUCKET}/paperless-db/${BACKUP_FILE} \
                --endpoint-url ${S3_ENDPOINT}

              echo "Backup ${BACKUP_FILE} uploaded successfully"

              # Cleanup old backups (keep 30 days)
              CUTOFF_EPOCH=$(($(date +%s) - 30 * 86400))
              CUTOFF_DATE=$(date -d @${CUTOFF_EPOCH} +%Y%m%d 2>/dev/null || date -r ${CUTOFF_EPOCH} +%Y%m%d)

              aws s3 ls s3://${S3_BUCKET}/paperless-db/ --endpoint-url ${S3_ENDPOINT} | \
                awk '{print $4}' | \
                while read -r file; do
                  if [ -n "$file" ]; then
                    FILE_DATE=$(echo $file | sed 's/paperless-db-\([0-9]\{8\}\).*/\1/')
                    if [ -n "$FILE_DATE" ] && [ "$FILE_DATE" != "$file" ] && [ "$FILE_DATE" -lt "$CUTOFF_DATE" ]; then
                      echo "Removing old backup: $file"
                      aws s3 rm s3://${S3_BUCKET}/paperless-db/${file} --endpoint-url ${S3_ENDPOINT}
                    fi
                  fi
                done

              echo "Cleanup complete"

            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: postgres-db
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ENDPOINT
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_BUCKET

            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
