apiVersion: v1
kind: Secret
metadata:
    name: umami-db-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:uHCS67o=,iv:0UgIio8cUXu47TEGSm0WOwJCLnOEms6eXei5FN/WRe4=,tag:GISKZvU2LOYZqAJd2aJwhQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lBf7841AfYMtYqOvg0que7j+kpFzkhDPyS9VVlBsnok2Eie5wgtZSzcZeY/kDgNXVjIN+g5ua1aq0mI8rJvMSQ==,iv:HqkbHxV9L4MlseXB35cINrZ/um84J+uYebV1IfCvrlM=,tag:YH76BNPUtYfvzGhzgTFtjQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:MvWDfQ8=,iv:2S3pyzQ047FOkhrj6X55TO04B2IJC/QSdSCPNqYhF6k=,tag:exnUxQQV+3X5RRj7wDggQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVjBhUXVOUVA5ak9FYUVI
            THB2RzR1UzN5V3dpcEEvTnF6QlV4WXlxbGk4ClVaL3Jxc24xSWlGVG5YTzVycGVK
            UkhKM251OC9VcFpoMmV2T1RlOWRtbjAKLS0tIHNUbGM0RkhHc0EzT0NVYlRMTmNX
            NVB4eDhLc0w5Vy9mdGhnRHRrSjNjcjgKPaWbE7eRWCM7Yh98Q4DBw1tKse9Xuka+
            VRXaBmm5cFcRQ6Z6dcNGENFNAmSjiiwtbLRS0800ffS9N0+U3SGv8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T15:25:54Z"
    mac: ENC[AES256_GCM,data:BhAE06bPKS6jlJTvJq7qnTWQ2/QqoVWj0x7GvIR5UxVkydDik6IVT875ajy4Gj8WDlo6zJPQV0ZG92ld597VT8ohbtmV+faZZVFikxd8nkSjaszzlhlN5ALfkngz69aErIMqxbHxz4Pz9rujIGnQKrSVa+aWsSy7b5E+6ZQelWA=,iv:05w+6vl62LhKSukTb6Xa9unxo3yydIMjBW0X92pQ/yg=,tag:783QIDGs7zD3pLPY0x2PeQ==,type:str]
    version: 3.13.2
