---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    # Identity issuer configuration
    identity:
      issuer:
        scheme: kubernetes.io/tls

    # Control plane resource limits (Phase 4 spec: 300m CPU, 200Mi RAM total)
    controllerResources:
      cpu:
        request: 100m
        limit: 500m
      memory:
        request: 100Mi
        limit: 256Mi

    destinationResources:
      cpu:
        request: 50m
        limit: 500m
      memory:
        request: 50Mi
        limit: 128Mi

    # Proxy defaults for sidecars (Phase 4 spec: 10m CPU, 15Mi RAM per sidecar)
    proxy:
      resources:
        cpu:
          request: 10m
          limit: 100m
        memory:
          request: 15Mi
          limit: 64Mi

    proxyInjector:
      namespaceSelector:
        matchExpressions:
          - key: config.linkerd.io/admission-webhooks
            operator: NotIn
            values:
              - disabled
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kube-system

    # Disable HA mode (single node cluster)
    controllerReplicas: 1
    enablePodAntiAffinity: false

    # Disable Prometheus integration (will add in Phase 7)
    prometheus:
      enabled: false
