---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    name: linkerd
    linkerd.io/is-control-plane: "true"
    config.linkerd.io/admission-webhooks: disabled
    pod-security.kubernetes.io/enforce: privileged
