---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: ">=8.0.0 <9.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminPassword: "changeme-rotate"  # rely on Authentik OAuth for access

    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/funnel: "false"  # Private to Tailscale network only
      hosts:
        - grafana-monitoring
      tls:
        - hosts:
            - grafana-monitoring

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            url: http://vmstorage:8428
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki:3100
            access: proxy
            isDefault: false

    env:
      GF_SERVER_ROOT_URL: "https://grafana-monitoring"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "HaGng4gJXBsZs6lgoNAot9OvDQdWTTDIkvjflR0t"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "zcpP7sjjE7phwu3SP7l1UpI1EzCELZz1BEkPv67FE7ywCmjg8aUZfqutNc5dCiWcrfw9m2XVaPx6zFzCaO6aZ43Lb9iFiuqHZTHdanFQn5DEMra6gTwDqyeMMNoGlI4B"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.primed.io/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.primed.io/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.primed.io/application/o/userinfo/"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.primed.io/application/o/grafana/end-session/"

    priorityClassName: monitoring

    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 400m
        memory: 512Mi

    podLabels:
      owner: platform
