---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-state-metrics
      version: ">=5.0.0 <6.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    replicas: 1
    podAnnotations:
      linkerd.io/inject: "disabled"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 256Mi
