---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    linkerd.io/inject: enabled
  labels:
    pod-security.kubernetes.io/enforce: privileged  # Required for Promtail hostPath volumes
