---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
  labels:
    owner: platform
spec:
  serviceAccountName: vmagent
  selectAllByDefault: true
  scrapeInterval: 30s
  externalLabels:
    cluster: k3s-primed
  remoteWrite:
    - url: http://vmstorage:8429/api/v1/write
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  nodeScrapeSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  staticScrapeSelector: {}
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podMetadata:
    annotations:
      linkerd.io/inject: "disabled"
