---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmstorage
  namespace: monitoring
  labels:
    owner: platform
spec:
  retentionPeriod: "30d"
  podMetadata:
    annotations:
      linkerd.io/inject: "disabled"
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 800m
      memory: 1536Mi
