---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: ">=3.3.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    validationFailureAction: Audit
    backgroundController:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
