---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  interval: 30m
  chart:
    spec:
      chart: vikunja
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: flux-system
      interval: 12h
  values:
    vikunja:
      image:
        repository: docker.io/vikunja/vikunja
        tag: "1.0.0"
        pullPolicy: IfNotPresent

      controller:
        labels:
          app: vikunja
          owner: nederhrj

      podAnnotations:
        linkerd.io/inject: "enabled"

      persistence:
        data:
          enabled: true
          accessMode: ReadWriteOnce
          size: 10Gi
          mountPath: /app/vikunja/files
          storageClass: local-path
        database:
          enabled: false

      service:
        main:
          ports:
            http:
              port: 3456

      ingress:
        main:
          enabled: false

      configMaps:
        config:
          enabled: false

      env:
        VIKUNJA_SERVICE_JWTSECRET:
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: jwt-secret
        VIKUNJA_DATABASE_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: postgres-password
        VIKUNJA_REDIS_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: redis-password
        VIKUNJA_AUTH_OPENID_PROVIDERS_0_CLIENTID:
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: oauth-client-id
        VIKUNJA_AUTH_OPENID_PROVIDERS_0_CLIENTSECRET:
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: oauth-client-secret

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
