apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nAlaB7JGno1O6Ulu/NGCrE8Z0c0k0czNfcx32Xbk7KUr/sHjVGDtJkQy3gXRcIXdcst3Km7GyLNCYnbSQGb+yIx7y7uAS++qBll0VFMuGlqzijpOMJUB4PBLFmmlYH7y/VW1E01LCa7qQ8HmighleUh+ZCT+wncul+px+khLrGh4S/cyWq16U36tb1UyW5naxpttT07l/2RxigtlzpfcxAony5HrPXIOBwzaIYYsbJSO661Jbaz0HVCHvohrJW7F9MqtcnYFD0RHMChwzv+n5V11E56ndG4Ul9n5OjttGFapolm2,iv:Oma76eD7UaMn7/2ggg7I8f/oU1MdehEV5C+S22pv8Po=,tag:6Ov4HgCv/nw5BBKF+bUOFw==,type:str]
kind: Secret
metadata:
    name: ghcr-cirthe-pull
    namespace: cirthe
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Nk9oSXVreUV4VHJpVmJr
            V1BGZHZBYytwMWkya2FQUlhwZGZINGhLa0Z3Cm5SWFpka3ZBSzVuUkhUYmJBSUVH
            YXZsVng1bkQ3Vm9CYVlRaEFkcFFwUkEKLS0tIFNET1lUbzJmeUN2QmMyWXQzWGpq
            WW1abzMyWWNkSEdOMGlicXByTVFMbVEKBpxbxr3VH7obA7GttpGo3iC3gGHxAdRr
            XmE4vOrsWFbReAsmCYroRdSVQzZYf/3gBhGHmAU/yhyQCxYW6+DMjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T13:09:01Z"
    mac: ENC[AES256_GCM,data:WAQiRoQyV4In4myo4ieeMMDjP18zWa7Caw6rOXLUiUnOpP/+n/+kOdHsoaluNA/QMEkqPqGDqBDz7k87RzRBM9o8g3Slbw0uhYpjtuJIZ+TWZY8z48FNLft//FEbpFsPFCFBbsCUbZXISt1e6soX3+x+CIe3fYBTARTepIaH99E=,iv:OEmv+WtKIwG0fAz4VTPaj5heDmfzJnTSKvk6Gg/nbWY=,tag:RIpaPmWhL7T9xd9gZpQqgQ==,type:str]
    version: 3.13.2
