apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cirthe
resources:
  - namespace.yaml
  - ghcr-pull-secret.enc.yaml
  - deployment.yaml
  - ingressroute.yaml
  - certificate.yaml
  - network-policies.yaml
images:
  - name: ghcr.io/cogfor/cirthe.com
    newName: ghcr.io/cogfor/cirthe.com
    newTag: sha-4fd298f10a4f3bd9c43b9b93225eab629838320e
    digest: sha256:fc66d1b1b657f148d79bc0a211b329084ba78ade6ca37b4839fcf53aadaf1b70
replicas:
  - name: cirthe
    count: 2
