apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cirthe
resources:
  - namespace.yaml
  - ghcr-pull-secret.enc.yaml
  - deployment.yaml
  - ingressroute.yaml
  - certificate.yaml
  - network-policies.yaml
images:
  - name: ghcr.io/cogfor/cirthe.com
    newName: ghcr.io/cogfor/cirthe.com
    newTag: sha-792876e7ee44fefbdd7ab90770487e4b6970d1e0
    digest: sha256:31a89d79487a6860237180edc4e6147ec2c7f945e9dce4aea0ebd3fdad655778
replicas:
  - name: cirthe
    count: 2
