---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniflux-tls
  namespace: miniflux
spec:
  secretName: miniflux-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - rss.primed.io
