---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2024.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 12h
  values:
    # Authentik server configuration
    authentik:
      secret_key: ""  # Provided by secret
      error_reporting:
        enabled: false
      postgresql:
        host: "postgres"
        port: 5432
        name: "authentik"
        user: "authentik"
        password: ""  # Provided by secret
      redis:
        host: "redis"
        password: ""  # Provided by secret

    # PostgreSQL subchart - DISABLED (using external StatefulSet)
    postgresql:
      enabled: false

    # Redis subchart - DISABLED (using external StatefulSet)
    redis:
      enabled: false

    # Server replicas
    server:
      replicas: 1
      podAnnotations:
        linkerd.io/inject: "disabled"
      envFrom:
        - secretRef:
            name: authentik-secrets
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: authentik-secret-key
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: "postgres"
        - name: AUTHENTIK_POSTGRESQL__USER
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: postgres-password
        - name: AUTHENTIK_POSTGRESQL__USE_SSL
          value: "false"
        - name: AUTHENTIK_POSTGRESQL__OPTIONS__sslmode
          value: disable
        - name: AUTHENTIK_REDIS__HOST
          value: "redis"
        - name: AUTHENTIK_REDIS__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: redis-password

      # Volume for media files
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
      volumeMounts:
        - name: media
          mountPath: /media

      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi

    # Worker configuration
    worker:
      replicas: 1
      podAnnotations:
        linkerd.io/inject: "disabled"
      envFrom:
        - secretRef:
            name: authentik-secrets
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: authentik-secret-key
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: "postgres"
        - name: AUTHENTIK_POSTGRESQL__USER
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: postgres-password
        - name: AUTHENTIK_POSTGRESQL__USE_SSL
          value: "false"
        - name: AUTHENTIK_POSTGRESQL__OPTIONS__sslmode
          value: disable
        - name: AUTHENTIK_REDIS__HOST
          value: "redis"
        - name: AUTHENTIK_REDIS__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: redis-password

      # Volume for media files
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
      volumeMounts:
        - name: media
          mountPath: /media

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
