---
# LDAP TLS Certificate
# Automatically created and renewed by cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-ldap-tls
  namespace: authentik
spec:
  secretName: authentik-ldap-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: ldap-selfsigned
    kind: Issuer
  commonName: ldap.authentik.svc.cluster.local
  dnsNames:
    - ldap.authentik.svc.cluster.local
    - ldap.primed.io
    - k3s.primed.io
