apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:2RP84leZ+328wV84hOJ7rXnJZ3A/JELpMV7BKFoyLLH6um2wwb7GUW+TJc4=,iv:KKjFo80CdlvsPp3FxIp58SsgNMzEWvJ54NpX4vlt5jM=,tag:SOaNf3z0JysRaYINT9mvLQ==,type:str]
    redis-password: ENC[AES256_GCM,data:V0OIE7DKUAcxDUGRE0mGjX8AB20wiLl7uUJkWovM+pNZIePT1J/Id7amUeY=,iv:wd3POFykKyk5mzLWHjiYarF019uk8CCHRF1lvlnE/DE=,tag:ybhZlOfuvZjgHdQ9qX0OrA==,type:str]
    authentik-secret-key: ENC[AES256_GCM,data:W0/0fRBCuiLAQZ7S+8wFWyJE3mthDDcsCmxmWnufbemjqG8u0iu2xe+hl01NSSccut979NGIRszT+84S8Kr+gyldV/xtwJnuXMOKAX9aInMrG+wm0t1X9w==,iv:3INFjAVKvz15yUGLcKysbIqgJMrhVeQBD0Tbs0WRBIk=,tag:tqEgEIPJik3E836j+0KAgQ==,type:str]
sops:
    age:
        - recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aVZrRi8ydTNlNlNQcnhV
            aEJUTUR2d3crcHJrTWxROFo1TExhUENOVFI0CmxCNUlaQzkwTkVtbFNxVGFraU5I
            enRhc1AwTVd5SGlsRUNyemxJQnVBVDgKLS0tIGxZaUpzSWgvOElsbHBidnJJTEJo
            bXZhKzg2SXZGbWxoRnZpRWwvdEo0MFEKKUY4M50XtdLiYtz6BnYI6PVDILJSKDjs
            IwP70nQfpLtyK6kCx535OAr5L9fe4NNBWGXLUVIW8sRv/5zh7ZIN/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T21:30:49Z"
    mac: ENC[AES256_GCM,data:z1e7+l7OnzfjTcA041CtWdhkxSz3WKFfFF/jMOOc6GwMY59Hh9o1rqaAA6qANjaDu71s2ZDKG9/pUzFMgKGzb1bsa9tUnRwDGINrUiV4RC+JyUT9KPB4zHOy3xRuOgBaQL9hgserBabRP/nQGUFIlPgkP7C8CUQeUq0W5YmH2BM=,iv:KD+E2HX1/8ijWpbH3BQ8X8RqP3TOt42NJgWqNEbDed8=,tag:efkOLQA881SeXb0YEBHQDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
